//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.BgEducations = new HashSet<BgEducation>();
            this.FtEducations = new HashSet<FtEducation>();
            this.LanguageCerts = new HashSet<LanguageCert>();
            this.Uploads = new HashSet<Upload>();
            this.WorkExps = new HashSet<WorkExp>();
        }
        public virtual BgEducation BgEducation { get; set; }
        public virtual FtEducation FtEducation { get; set; }
        public virtual LanguageCert LanguageCert { get; set; }
        public virtual WorkExp WorkExp { get; set; }
        public Upload Upload { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string CountryofBirth { get; set; }
        public string CitizenshipMain { get; set; }
        public string PlaceofBirth { get; set; }
        public string FatherName { get; set; }
        public string FatherSurname { get; set; }
        public string MotherName { get; set; }
        public string MotherSurname { get; set; }
        public string PhoneNumber { get; set; }
        public string maritalStatus { get; set; }
        public string PassaportNumber { get; set; }
        public Nullable<System.DateTime> PassStartDate { get; set; }
        public Nullable<System.DateTime> PassExpireDate { get; set; }
        public string IssuingCountry { get; set; }
        public string IssuingAuthority { get; set; }
        public string NationalId { get; set; }
        public Nullable<System.DateTime> IdStartDate { get; set; }
        public Nullable<System.DateTime> IdExpireDate { get; set; }
        public string CountryCitizenship { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Email { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BgEducation> BgEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FtEducation> FtEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageCert> LanguageCerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Upload> Uploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkExp> WorkExps { get; set; }
    }
}
