//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BgEducation
    {
        public int ID { get; set; }
        public string InstitutionName { get; set; }
        public string Faculty { get; set; }
        public string InsturactionLang { get; set; }
        public string InsCountry { get; set; }
        public string StudyMode { get; set; }
        public string EducationLevel { get; set; }
        public Nullable<System.DateTime> EducationStDate { get; set; }
        public Nullable<System.DateTime> EducationCompDate { get; set; }
        public Nullable<double> AvarageGrade { get; set; }
        public bool Awarded { get; set; }
        public Nullable<int> AppID { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
