//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FtEducation
    {
        public int ID { get; set; }
        public string Country1 { get; set; }
        public string Country2 { get; set; }
        public string FieldOfStudy { get; set; }
        public string EducationLevel { get; set; }
        public string Intake { get; set; }
        public Nullable<int> AcademicYear { get; set; }
        public int AppId { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
