//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageCert
    {
        public int ID { get; set; }
        public Nullable<bool> LangCert { get; set; }
        public string CertType { get; set; }
        public string CertNoIELTS { get; set; }
        public string CertOtherIELTS { get; set; }
        public string OverallScoreIELTS { get; set; }
        public Nullable<System.DateTime> TestDateIELTS { get; set; }
        public Nullable<double> ListeningIELTS { get; set; }
        public Nullable<double> ReadingIELTS { get; set; }
        public Nullable<double> WritingIELTS { get; set; }
        public Nullable<double> SpeakingIELTS { get; set; }
        public Nullable<int> ListeningTOEFL { get; set; }
        public Nullable<int> ReadingTOEFL { get; set; }
        public Nullable<int> WritingTOEFL { get; set; }
        public Nullable<int> SpeakingTOEFL { get; set; }
        public Nullable<int> AppId { get; set; }
        public string OverallScoreTOEFL { get; set; }
        public Nullable<System.DateTime> TestDateTOEFL { get; set; }
        public string CertNoTOEFL { get; set; }
        public string CertOtherTOEFL { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
