//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentAppEntities : DbContext
    {
        public StudentAppEntities()
            : base("name=StudentAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<BgEducation> BgEducations { get; set; }
        public virtual DbSet<FtEducation> FtEducations { get; set; }
        public virtual DbSet<LanguageCert> LanguageCerts { get; set; }
        public virtual DbSet<LocalUser> LocalUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Upload> Uploads { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkExp> WorkExps { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
