//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public int Id { get; set; }
        public string FileType { get; set; }
        public string FilePath { get; set; }
        public int AppId { get; set; }
        public string FileName { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
